ci:
  collect:
    staticDistDir: ./public
  assert:
    preset: lighthouse:recommended
    assertions:
      installable-manifest: "off"
      meta-description: "off"
      offline-start-url: "off"
      service-worker: "off"
      splash-screen: "off"
      themed-omnibox: "off"
      works-offline: "off"
  upload:
    target: temporary-public-storage
