version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/study-lighthouse-ci
    steps:
      - checkout
      - run: npm i
      - run: npm run collect
      - run: npm run upload
